### ISSUE TITLE
no configuration file specified

### ISSUE THREAD

**Issue by mircealungu** [flask-dashboard/Flask-MonitoringDashboard#107]
why do i get this `No configuration file specified. Please do so.`? 
i thought we should be able to collect_performance only with command line arguments. or?

```
$ python -m flask_monitoringdashboard.collect_performance --test_folder ./tests_zeeguu_api/ --url https://zeeguu.unibe.ch/api/dashboard
Starting the collection of performance results with the following settings:
  - folder containing unit tests:  ./tests_zeeguu_api/
  - number of times to run tests:  5
  - url to submit the results to:  https://zeeguu.unibe.ch/api/dashboard
ZEEGUU: Loaded testing configuration.
ZEEGUU: Linked model with: sqlite:///:memory:
No configuration file specified. Please do so.

```

**Comment by mircealungu** [comment]
mother of all mysteries, I only get that on my machine.
on travis this seems to work!
why would this be?

**Comment by kloostert** [comment]
This message comes from the initialization of the Dashboard, since every time the tests are run, an app object will be instantiated (and if bound to the Dashboard, it will be instantiated as well).
But this does not affect the unit testing part, and thus it should still work regardless of this message.
The most recent code is on the dev branch, where this message will be omitted whenever the code is running on Travis.
The reason why you are not getting the message on Travis at the moment is probably because of [this line](https://github.com/zeeguu-ecosystem/Zeeguu-API/blob/d2b7fd2c29dd76d4a828011ced0ac10c11a411bb/.travis.yml#L16).
Line 18 can also be left out, and line 17 was your original script call for testing Zeeguu.

I see that Zeeguu uses the latest version from pypi, and so the new functionality will only come into effect after the dev branch has merged with master and a corresponding version is uploaded to pypi.

**Comment by kloostert** [comment]
The new functionality has now been merged into master and uploaded to pypi. 
If all is well, the Travis configuration of Zeeguu should work better now.
