### ISSUE TITLE
Including information about database queries

### ISSUE THREAD

**Issue by Harold2017** [flask-dashboard/Flask-MonitoringDashboard#139]
Hi,
May you guys have interest in adding a query record feature in your measurement wrapper or outlier thread?
I think the get_debug_queries function from flask-sqlalchemy may help.
Thanks!

**Comment by FlyingBird95** [comment]
I think that you're referring to this: http://flask-sqlalchemy.pocoo.org/2.3/api/#flask_sqlalchemy.get_debug_queries

As the Flask-MonitoringDashboard is a plugin for an existing Flask Application, I think that it would make more sense to configure this in the Flask application, rather than in the Dashboard.

But thanks for noticing this!

Patrick

**Comment by Harold2017** [comment]
Hi Patrick,

Yep, i use it in my Flask app and stored slower query records in db for generating a statistical chart. I think integrating it into dashboard may be a good idea for consistency. I do not know whether you have plans for exposing some APIs for custom plots in this dashboard app but i hope so.
Thanks!

Harold
