### ISSUE TITLE
Unable to access request context in group_by

### ISSUE THREAD

**Issue by AeonLucid** [flask-dashboard/Flask-MonitoringDashboard#240]
I am unable to access request context in `dashboard.config.group_by`.
The [docs](https://flask-monitoringdashboard.readthedocs.io/en/latest/functionality.html) say "replace with a function to retrieve the id of the user within a request.".

```python
def get_key():
    headers = request.headers
    # Wont reach here because line above crashes.
    return headers.get("X-Key", 'default')

dashboard.config.group_by = get_api_key
```

Is this intended? How can I fix my issue?

**Comment by bogdanp05** [comment]
Hi @AeonLucid! Thanks for signalling the issue. I was able to replicate it.
Indeed, the problem seems to be that we try to resolve the `group_by` outside the request context, in a separate thread started [here](https://github.com/flask-dashboard/Flask-MonitoringDashboard/blob/8024e775aee7e1fa4f18bfadcfd0ba55094086c6/flask_monitoringdashboard/core/profiler/__init__.py#L27).

One solution could be to resolve the `group_by` function right before starting that thread, because then you are still inside the request context.
We are quite busy for the next two weeks, so I'm not sure if we'll find the time to fix this by then. However, we are always happy to accept contributions, so feel free to submit a PR if you want to fix it yourself.:)

**Comment by AeonLucid** [comment]
I have submitted a PR with your proposed solution.

**Comment by bogdanp05** [comment]
That was really fast, thanks for your contribution!
