### ISSUE TITLE
Sorting is done textually instead of numerically

### ISSUE THREAD

**Issue by ehiggs** [flask-dashboard/Flask-MonitoringDashboard#295]
**Describe the bug**
When sorting by median time of a request, `90 ms` is sorted above `800 ms`.

**To Reproduce**
Click the column headings in the table.

**Expected behavior**
`800 ms` to be sorted above `90 ms`. And `1 sec` to be sorted above `900 ms`.

**Desktop (please complete the following information):**
Firefox 73 OS X.

**Comment by mircealungu** [comment]
Hi @ehiggs !

Thanks for the observation. 
The bug is fixed in https://github.com/flask-dashboard/Flask-MonitoringDashboard/commit/09cab9a332b9858116cda4db0a1773fbd01b510e

It'll be part of the next release of FMD!

In the meantime, if you could fill in the FMD survey we'd be thankful :)
https://docs.google.com/forms/d/e/1FAIpQLSe90H1a-Toz6YmsjwAB8SHEp6SSjcR8BaGrKHkHYpq8EqQQzQ/viewform
