### ISSUE TITLE
build is broken for Python 2.7 and 3.5

### ISSUE THREAD

**Issue by mircealungu** [flask-dashboard/Flask-MonitoringDashboard#299]
Errors are here:

Python 2.7
https://travis-ci.org/flask-dashboard/Flask-MonitoringDashboard/jobs/655435643?utm_medium=notification&utm_source=email

Python 3.5
https://travis-ci.org/flask-dashboard/Flask-MonitoringDashboard/jobs/655435644?utm_medium=notification&utm_source=email

the second is because somewhere in one dependency (i.e. Jinja) there's a f"string .

I wonder if it's maybe safe to simply drop support for Python 2.7 and 3.5...

**Comment by bogdanp05** [comment]
Hi @mircealungu ! I compared the logs of the failed job with the logs of a [previous successful job](https://travis-ci.org/flask-dashboard/Flask-MonitoringDashboard/jobs/634763618?utm_medium=notification&utm_source=github_status) for Python 3.5. The failing job uses Jinja2 3.0.0, while the successful one use Jinja2 2.10.3. 

We don't have Jinja2 in our `requirements.txt`, but the problem is that one of the packages that we use and is dependent on Jinja2 (I think Flask) probably has in its requirements something like `Jinja2>=2.10.1`. 

My solution would be to include in our requirements `Jinja2==2.10.3` (or whatever the latest stable version is). This way, we don't drop support for Python 3.5.

And maybe, to prevent future problems, we should fix the versions of all the packages in our `requirements.txt`.

**Comment by mircealungu** [comment]
Thanks @bogdanp05 ! Indeed, pinning the Jinja2 dependency has fixed the issue. 

BTW, how did you compare the logs? Plain diff is quite noisy.

**Comment by bogdanp05** [comment]
Great! 

> BTW, how did you compare the logs? Plain diff is quite noisy.

The good old fashion way :) - looked at the error, checked the package version, compared it with the Jinja2 version in a passing log

**Comment by mircealungu** [comment]
Fair enough :)
I'll close this since it's fixed now.
A nice Friday!
M>

**Comment by mircealungu** [comment]
Fixed in https://github.com/flask-dashboard/Flask-MonitoringDashboard/commit/4b975a23d6595f2f840b6c9c01dbf9812c1e0a9d
