### ISSUE TITLE
Live Demo no longer available at link

### ISSUE THREAD

**Issue by caffeinatedMike** [flask-dashboard/Flask-MonitoringDashboard#305]
The Live Demo now leads to an empty Heroku web app. Any chance the demo can be put back up? I'd love to check it out. I'm especially interested to see if the dashboard is mobile friendly. Thanks!

**Comment by FlyingBird95** [comment]
Hey @caffeinatedMike ,

Thanks for notifying this problem! It is indeed true that the Master branch of the heroku is currently broken, since we just updated the feature of automatically deploying a release to heroku. The development branch works fine on heroku and can be viewed at: https://fmd-development.herokuapp.com

After the new version is merged to master, the dashboard at https://fmd-master.herokuapp.com will work again!

I apologise for the inconvenient,

Patrick

**Comment by caffeinatedMike** [comment]
@FlyingBird95 No worries, thanks for explaining!
