### ISSUE TITLE
Credentials not updated from configuration file

### ISSUE THREAD

**Issue by curziobasso** [flask-dashboard/Flask-MonitoringDashboard#385]
**Describe the bug**
The credentials of the admin user are not updated when changed in the configuration (using postgresql as db).

**To Reproduce**
1. Start from a working dashboard with an already existing admin user.
2. Change the user credentials in the config file.
3. Restart the server.
4. Try to log with the new credentials.
5. Authentication fails.

**Expected behavior**
I would expect credentials to be automatically updated.
Rather, I have to delete the previous admin user from the DB table in order for the credentials to be updated.

**Desktop (please complete the following information):**
 - OS: MacOS 11.2.3
 - Browser: Firefox 88
 - FMD: 3.1.0

**Additional context**
The Flask app and postgresql (v11) run in two different containers, sharing the same network.
We use the following environment (showing only the relevant packages):
connexion==2.6.0
Flask==1.1.2
Flask-MonitoringDashboard==3.1.0
psycopg2-binary==2.8.6
SQLAlchemy==1.4.12

**Comment by alexander34ro** [comment]
Hi @curziobasso,

This behavior seems to be by design. FMD supports multiple admin accounts, so automatically updating the default credentials is not trivial. The expected behavior you described makes sense if you are using a single admin account, but I'm not sure how this would work for multiple accounts.

I also reproduced this on the default SQLite database so this is unrelated to the PG setup. 

Checking `flask_monitoringdashboard/database/auth.py#get_user`, the admin credentials are only updated when there is no admin user in the database.

```python
"""Validates the username and password and returns an User-object if both are valid.
In case the User-table is empty, a user with default credentials is added.
"""
...
if session.query(User).count() == 0:
    user = User(username=config.username, is_admin=True)
    user.set_password(password=config.password)
    session.add(user)
```

@mircealungu I think the desired change (_automatically updating the credentials when the config file is changed_) would be quite intrusive. When the config is changed, we have no reference of the previous admin credentials so even though we could add a new user with those credentials, we can't delete the previous admin user since there could be multiple admins added manually.

**Comment by curziobasso** [comment]
Hi @alexander34ro, I see what you mean.
 
It was a misunderstaning on my side, but I think it would be worthwhile mentioning it in the documentation: I think it might be a common situation in actual deployments.

In any case, a really nice project, thank you!
