### ISSUE TITLE
ModuleNotFoundError: No module named 'requests'

### ISSUE THREAD

**Issue by 9tin9tin9** [flask-dashboard/Flask-MonitoringDashboard#445]
**Describe the bug**
I am using Flask-MonitoringDashboard inside pipenv. When I start my flask server with `flask run`, it gives the error
```
Error: While importing 'app', an ImportError was raised:

Traceback (most recent call last):
  File "/Users/austinsiu/.local/share/virtualenvs/BackendApp_python-Vvhl7s2y/lib/python3.10/site-packages/flask/cli.py", line 219, in locate_app
    __import__(module_name)
  File "/Users/austinsiu/Desktop/program/ChatClone/BackendApp_python/app/__init__.py", line 46, in <module>
    dashboard.bind(app)
  File "/Users/austinsiu/.local/share/virtualenvs/BackendApp_python-Vvhl7s2y/lib/python3.10/site-packages/flask_monitoringdashboard/__init__.py", line 50, in bind
    from flask_monitoringdashboard.views import (
  File "/Users/austinsiu/.local/share/virtualenvs/BackendApp_python-Vvhl7s2y/lib/python3.10/site-packages/flask_monitoringdashboard/views/deployment.py", line 8, in <module>
    from flask_monitoringdashboard.core.telemetry import post_to_back_if_telemetry_enabled
  File "/Users/austinsiu/.local/share/virtualenvs/BackendApp_python-Vvhl7s2y/lib/python3.10/site-packages/flask_monitoringdashboard/core/telemetry.py", line 2, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

I could not find any place mentioning I also need the `request` module in order to use Flask-MonitoringDashboard.

Also one question, is there any way to disable telemetry in configuration?

**Desktop (please complete the following information):**
 - OS: MacOS 12.7.1
 - Browser: Not even this step
 - FMD Version: 3.2.2

**Comment by wielas** [comment]
Hi @9tin9tin9! Thanks for submitting the issue - that's a major oversight on our part. Requests module is used for telemetry purposes and the fix for the requirements is coming in a soon-to-be-released version along an extra database pruning functionality and other bugfixes. For now you can just run `pip install requests` to fix the issue if you haven't already. Sorry!

Regarding the question about disabling telemetry - it's absolutely possible. There is a tab inside the configuration that allows you to opt-out whenever you like. However, we'll be obliged if you consider sharing the usage data - it helps us a lot with the research we're currently conducting on our university!

**Comment by 9tin9tin9** [comment]
Thanks for the reply!

I hope telemetry can be disabled in places like
```python
app = Flask(__name__)
dashboard.bind(app, telemetry=False)
```
or in a config dictionary

Looking forward to your new release!

**Comment by wielas** [comment]
The telemetry is off by default -- you'll only be sharing the data if you explicitly give consent for it on the prompt on /overview endpoint or in the configuration tab. There's no option to turn off the prompts right now and I know that we're being a little bit pushy asking for consent, but we'll most likely turn off the entire telemetry feature once we've collected enough data to make a meaningful analysis and guide the future FMD development :)

^ this is a feedback that helps us a lot though!
