### ISSUE TITLE
Static file statistics error

### ISSUE THREAD

**Issue by 0v0** [flask-dashboard/Flask-MonitoringDashboard#49]
Hi, great job on the monitor. I am a python developer loves flask as well.
But I found some problem in the current version about static file access.
Here I attached the error prompt when accessing static files if `/<path:filename>` was ticked.

![image](https://user-images.githubusercontent.com/4048169/36187631-96edd772-1181-11e8-9a01-7e2426a2c6d7.png)

Thanks!

**Comment by kloostert** [comment]
I have tried to replicate this error using the most recent version of the Flask-MonitoringDashboard, but I was not able to; it seems to work now.
Also, since this error was posted a few months ago, this issue will be closed now.
If someone encounters this error again in the newest release, please do create a new issue along with some steps to replicate the error.
