### ISSUE TITLE
endpoint not being tracked still shows up in Version Usage

### ISSUE THREAD

**Issue by mircealungu** [flask-dashboard/Flask-MonitoringDashboard#70]
i just removed the /validate endpoint from the ones being tracked. 
however, it still shows up in the Version Usage. 

is this right?

**Comment by FlyingBird95** [comment]
Yes, because it shows all endpoints that you've monitored throughout the lifetime of the Dashboard.

This allows you to see whether endpoint A is measured until version i and endpoint B is started from version i+1. Then, you can use this view to detect whether endpoint B is a renamed version of endpoint A.

**Comment by mircealungu** [comment]
fair enough. 
a little reason for the views might be useful in their vicinity. 
otherwise, not even we remember they why's :)
