### ISSUE TITLE
TF/IDF over the different endpoints considered as documents

### ISSUE THREAD

**Issue by mircealungu** [flask-dashboard/Flask-MonitoringDashboard#85]
all the stack traces in an endpoint could be one document. 

what are the terms that stand out?

**Comment by bogdanp05** [comment]
I computed the TF/IDF for the outliers. I used 1 corpus made up of all the stack traces of the outliers. I used the following custom stop words, which are not that relevant: `['br', 'buffer', 'client', 'daemon', 'egg', 'file', 'get', 'in', 'lib', 'line', 'local', 'py', 'python', 'packages', 'read', 'request', 'requests', 'return', 'self', 'send','site', 'ssl', 'url', 'urllib', 'usr', 'thread']`. I also removed all numbers, using a regex.

For instance, for the stack trace of an outlier from `api.get_possible_translations`, I got the following top terms:
```
python_translators> 0.4626110978341939
translators> 0.23130554891709695
started> 0.21762837715193717
threading> 0.20393013071901334
send_translation_request> 0.15883716114307694
microsoft_translator> 0.1550313245761273
chunked> 0.15431363372386667
connectionpool> 0.154224468405359
sessions> 0.15404649819431876
dashboard> 0.14761626706281214
```

How should I proceed? One approach could be to generate one corpus per endpoint, instead of one global corpus. Then, it is likely that for an endpoint like  `api.get_possible_translations` , the "google" and "microsoft" terms will stand out more.

**Comment by mircealungu** [comment]
now i see this message.
this is interesting. 

what do you get if you run the current algo for other enpoints, particularly: 

get_feed_items_with_metrics
bookmarks_to_study
report_exercise_outcome

**Comment by bogdanp05** [comment]
I attached the text files containing the top 10 words for each outlier of the 3 endpoints, plus the `get_possible_translations` endpoint. I expanded the stop words list a bit and it now looks like this: `['__init__', 'body', 'br', 'buffer', 'client', 'daemon', 'dashboard', 'egg', 'endpoint', 'file',
                     'get', 'http',  'headers', 'in', 'lib','line', 'local', 'py', 'python', 'packages', 'read',
                     'request', 'requests', 'return', 'run', 'self', 'send','site', 'ssl', 'started', 'url', 'urllib',
                     'usr', 'thread', 'threading']`

I also implemented an algorithm that uses one tf/idf corpus per endpoint. As far as I can tell, the results look more promising. For `get_possible_translations`, when doing a simple search for 'microsoft' or 'google', there are more matches among the list of the top 10 words for the outliers. Should I also upload the results for this algorithm? 

[api_get_feed_items_with_metrics.txt](https://github.com/flask-dashboard/Flask-MonitoringDashboard/files/1937634/api_get_feed_items_with_metrics.txt)
[api_bookmarks_to_study.txt](https://github.com/flask-dashboard/Flask-MonitoringDashboard/files/1937636/api_bookmarks_to_study.txt)
[api_report_exercise_outcome.txt](https://github.com/flask-dashboard/Flask-MonitoringDashboard/files/1937638/api_report_exercise_outcome.txt)
[api_get_possible_translations.txt](https://github.com/flask-dashboard/Flask-MonitoringDashboard/files/1937640/api_get_possible_translations.txt)

**Comment by bogdanp05** [comment]
We decided against this approach, since the results didn't look so promising. The new approach is in #164.
