### ISSUE TITLE
Need information regarding when the logs are written in database

### ISSUE THREAD

**Issue by iambibhas** [flask-dashboard/Flask-MonitoringDashboard#90]
Hi,

I don't have an issue to report, so not following the template. Rather, I need some information. I'm trying to figure out when the logs are written to the database to have an idea if the end performance will take any hit if, let's say, the db this library is writing to is blocked for some reason. Is the write done in a background job? I went through the code but didn't see that happening. I think you're using a decorator to wrap the views and then log their time taken with a direct function call and inside that the db is being written. Am I write?

Can you please clarify how much, if any, performance hit I can expect on a high traffic site?

Thanks for all the great work. Hope to contribute to this library sometime. :)

**Comment by kloostert** [comment]
Hi iambibhas,

Thank you for showing your interest in this project! 
It is indeed like you said, the views are wrapped by a function in order to track the time it takes for the endpoint to execute. Inside this wrapper function, the gathered information is directly stored in the database by executing a query on that database.  Looking into making this persistence process a background job might indeed be a good suggestion for this project. 
As for the performance overhead of the Dashboard, we would like to refer to [this paper](https://github.com/flask-dashboard/ICSME-18-Paper/blob/master/paper.pdf), more specifically Section VIII. I hope this answers your questions. If there is anything else we could clarify or assist with, please do not hesitate to ask us.
